version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_split_expenses
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"